const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Behaviors.Anchor,
		C3.Plugins.TiledBg,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.MoveTo,
		C3.Plugins.AJAX,
		C3.Plugins.TextBox,
		C3.Plugins.video,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Pathfinding.Acts.ClearObstacles,
		C3.Behaviors.Pathfinding.Acts.AddObstacle,
		C3.Behaviors.Pathfinding.Acts.RegenerateMap,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.Browser.Acts.LockOrientation,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Text.Acts.Destroy,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Text.Exps.Count,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetHAlign,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TextBox.Acts.SetPos,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.System.Exps.find,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.video.Acts.SetPos,
		C3.Plugins.video.Acts.SetSize,
		C3.Plugins.video.Acts.SetVisible,
		C3.Plugins.video.Acts.SetMuted,
		C3.Plugins.video.Acts.SetLooping,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.Browser.Acts.GoToURL
	];
};
self.C3_JsPropNameTable = [
	{lastFacing: 0},
	{Pin: 0},
	{Cat: 0},
	{Value: 0},
	{pooppower: 0},
	{Touch: 0},
	{Keyboard: 0},
	{Audio: 0},
	{Browser: 0},
	{Anchor: 0},
	{startoverlay: 0},
	{floors: 0},
	{Sprite: 0},
	{TiledBackground: 0},
	{bed: 0},
	{Sprite2: 0},
	{mat: 0},
	{chair: 0},
	{Sprite3: 0},
	{dresser: 0},
	{z: 0},
	{vz: 0},
	{groundH: 0},
	{onGround: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{Solid: 0},
	{CatHB: 0},
	{bedblocker: 0},
	{tv: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{pooppwer: 0},
	{pawprit: 0},
	{Pbar: 0},
	{bedtex: 0},
	{bedt1tx: 0},
	{bedt1tx2: 0},
	{Carpettx: 0},
	{dresstable: 0},
	{tvstantx: 0},
	{Ottomantx: 0},
	{chartx: 0},
	{Pathfinding: 0},
	{MoveTo: 0},
	{Maddy: 0},
	{Sprite7: 0},
	{upbtn: 0},
	{rightbtn: 0},
	{downbtn: 0},
	{leftbtn: 0},
	{jumpbtn: 0},
	{wall: 0},
	{Gameover: 0},
	{Winscreen: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Timer: 0},
	{Score: 0},
	{AddScore: 0},
	{clickblocker: 0},
	{Sprite10: 0},
	{Namebox: 0},
	{Submit: 0},
	{Sprite11: 0},
	{engamedance: 0},
	{Sprite12: 0},
	{eastegg: 0},
	{Button: 0},
	{viewleaderboard: 0},
	{MaddyChase: 0},
	{GameStarted: 0},
	{GameWin: 0},
	{TimeToChase: 0},
	{GameLose: 0},
	{PoopPower: 0},
	{elapsed: 0},
	{timerRunning: 0},
	{RoundTImeMS: 0},
	{eastereggplay: 0},
	{PlayerName: 0},
	{Payload: 0},
	{idletimer: 0},
	{PawCount: 0}
];

self.InstanceType = {
	Cat: class extends self.ISpriteInstance {},
	pooppower: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	startoverlay: class extends self.ISpriteInstance {},
	floors: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	bed: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	mat: class extends self.ISpriteInstance {},
	chair: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	dresser: class extends self.ISpriteInstance {},
	CatHB: class extends self.ISpriteInstance {},
	bedblocker: class extends self.ISpriteInstance {},
	tv: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	pooppwer: class extends self.ISpriteInstance {},
	pawprit: class extends self.ISpriteInstance {},
	Pbar: class extends self.ISpriteInstance {},
	bedtex: class extends self.ITextInstance {},
	bedt1tx: class extends self.ITextInstance {},
	bedt1tx2: class extends self.ITextInstance {},
	Carpettx: class extends self.ITextInstance {},
	dresstable: class extends self.ITextInstance {},
	tvstantx: class extends self.ITextInstance {},
	Ottomantx: class extends self.ITextInstance {},
	chartx: class extends self.ITextInstance {},
	Maddy: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	upbtn: class extends self.ISpriteInstance {},
	rightbtn: class extends self.ISpriteInstance {},
	downbtn: class extends self.ISpriteInstance {},
	leftbtn: class extends self.ISpriteInstance {},
	jumpbtn: class extends self.ISpriteInstance {},
	wall: class extends self.ISpriteInstance {},
	Gameover: class extends self.ISpriteInstance {},
	Winscreen: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Timer: class extends self.ITextInstance {},
	Score: class extends self.IInstance {},
	AddScore: class extends self.ISpriteInstance {},
	clickblocker: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Namebox: class extends self.ITextInputInstance {},
	Submit: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	engamedance: class extends self.IWorldInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	eastegg: class extends self.IWorldInstance {},
	Button: class extends self.IButtonInstance {},
	viewleaderboard: class extends self.ISpriteInstance {}
}